name: test-app
type: laravel
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
use_dns_when_possible: true
composer_version: "2"
web_environment: []
# Include Supabase environment
docker-compose:
  - docker-compose.supabase.yaml
corepack_enable: false

